export const environment = {
  // production: true,
  // url: "https://prd-api.goarrival.com/security/v1/",
  // url_2: "https://prd-api.goarrival.com/flight/v1/",
  // url_5: 'https://prd-api.goarrival.com/customer/v1/',
  // url_6: 'https://domiruth-prd.azure-api.net/notify/',
  // url_hotel: "https://prd-api.goarrival.com/hotel/v1/",
  // urlIp: 'https://api.ipify.org/?format=json',
  // urlVisa: 'https://prd-api.goarrival.com/visa/v1/',
  // url_insurance: 'https://prd-api.goarrival.com/insurance/v1/',
  // urlVisaSource: 'https://static-content.vnforapps.com/v2/js/checkout.js',
  // url_reports: "http://reports-api.domiruth.com/api/",
  // url_project: "https://localhost:4200",
  // url_policy: "https://prd-api.goarrival.com/policy/v1/",
  // cod_rol_autogestion: [1],
  // cod_rol_autorizador: [2],
  // cod_rol_centralizador: [3],
  // url_cars: "https://prd-api.goarrival.com/cars/v1/",
  // baseUrl: 'https://prd-api.goarrival.com/vacation/v1/',
  // max_pax: 8,
  // url_bnus: 'https://ws-bnu.domiruth.com/api/',
  // key: '6dc253fab6fe416f94228951005b485a',
  // url_reportGeneral: 'https://prd-api.goarrival.com/report/v1/',
  // url_customer: 'https://prd-api.goarrival.com/customer/v1/'

  production: false,
  url: "https://uat-api.goarrival.com/security/v1/",
  url_2: "https://uat-api.goarrival.com/flight/v1/",
  url_5: 'https://uat-api.goarrival.com/customer/v1/',
  url_6: 'https://uat-api.goarrival.com/notification/v1/',
  url_reports: "http://reports-api.domiruth.com/api/",
  url_hotel: "https://uat-api.goarrival.com/hotel/v1/",
  url_insurance: 'https://uat-api.goarrival.com/insurance/v1/',
  url_policy: "https://uat-api.goarrival.com/policy/v1/",
  baseUrl: 'https://uat-api.goarrival.com/vacation/v1/',
  urlIp: 'https://api.ipify.org/?format=json',
  urlVisa: 'https://uat-api.goarrival.com/visa/v1/',
  urlVisaSource: 'https://static-content-qas.vnforapps.com/v2/js/checkout.js?qa=true',
  url_project: "http://sigvplus.azurewebsites.net",
  cod_rol_autogestion: [1],
  cod_rol_autorizador: [2],
  cod_rol_centralizador: [3],
  max_pax: 8,
  url_bnus: 'https://ws-bnu.domiruth.com/api/',
  key: "eb85131bc9d94c02840aa6961e7f77e9",
  url_reportGeneral: 'https://uat-api.goarrival.com/report/v1/',
  url_customer: 'https://uat-api.goarrival.com/customer/v1/',
  url_cars: "https://uat-api.goarrival.com/cars/v1/"
};
